// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villas_VillaApi.Data;

#nullable disable

namespace Villas_VillaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230921204940_AddDataToVillaTableToDb")]
    partial class AddDataToVillaTableToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Villas_VillaApi.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("double");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 9, 21, 21, 49, 40, 312, DateTimeKind.Local).AddTicks(5778),
                            Details = "This is a Magniificient Villa",
                            ImageUrl = "",
                            Name = "Royal Villa",
                            Occupancy = 2,
                            Rate = 1000.0,
                            Sqft = 760,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 9, 21, 21, 49, 40, 312, DateTimeKind.Local).AddTicks(5798),
                            Details = "This is a Magnificient Villa with a Pool",
                            ImageUrl = "",
                            Name = "Royal Pool Villa",
                            Occupancy = 4,
                            Rate = 1500.0,
                            Sqft = 1000,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 9, 21, 21, 49, 40, 312, DateTimeKind.Local).AddTicks(5799),
                            Details = "This is a Premium Villa with exquisite taste",
                            ImageUrl = "",
                            Name = "Premium Villa",
                            Occupancy = 2,
                            Rate = 2000.0,
                            Sqft = 1560,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 9, 21, 21, 49, 40, 312, DateTimeKind.Local).AddTicks(5801),
                            Details = "This is a premium villa with exquisite taste and a pool",
                            ImageUrl = "",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Rate = 4000.0,
                            Sqft = 2100,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 9, 21, 21, 49, 40, 312, DateTimeKind.Local).AddTicks(5803),
                            Details = "This is a luxuriously exqusite and lavish villa",
                            ImageUrl = "",
                            Name = "Diamond Villa",
                            Occupancy = 4,
                            Rate = 7000.0,
                            Sqft = 3600,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
